Add possible solutions to error messages of 'acpi_call' module

diff --git a/build/ux430ua-fan-control b/build/ux430ua-fan-control
--- a/build/ux430ua-fan-control
+++ b/build/ux430ua-fan-control
@@ -25,15 +25,19 @@ done
 
 # check if 'acpi_call' module loaded
 if ! lsmod | grep -q -E -e '^[[:blank:]]*acpi_call[[:blank:]].*$'; then
-    echo "$0: Required module 'acpi_call' is not loaded, action canceled." >&2
-    echo "$0: Possible solution: reboot your device." >&2
+    echo "$0: Required module 'acpi_call' is not loaded, action canceled.
+POSSIBLE SOLUTIONS:
+  * install program dependencies
+  * reboot your device" >&2
     exit 1
 fi
 
 # check if interface file for 'acpi_call' module exists
-if [ ! -f /proc/acpi/call ]; then
-    echo "$0: Interface file '/proc/acpi/call' for ACPI doesn't exist, action canceled." >&2
-    echo "$0: Possible solution: reboot your device." >&2
+if [ -f /proc/acpi/call ]; then
+    echo "$0: Interface file '/proc/acpi/call' for 'acpi_call' module doesn't exist, action canceled.
+POSSIBLE SOLUTIONS:
+  * install program dependencies
+  * reboot your device" >&2
     exit 1
 fi
 
