Add support for TAB completion for BASH

diff --git a/make/deploy b/make/deploy
--- a/make/deploy
+++ b/make/deploy
@@ -143,6 +143,19 @@ POSSIBLE SOLUTIONS:
     exit 1
 }
 
+# check if bash shell is used on this system
+if grep -q -E -e '^/bin/bash$' /etc/shells; then
+    # set up TAB completion for bash shell
+    mkdir -p /etc/bash_completion.d/ &&
+    cp "$SRC_DIR/asus-fan-control-completion" /etc/bash_completion.d/ || {
+        echo "$0: Can't set up TAB completion.
+POSSIBLE SOLUTIONS:
+  * Uninstall asus-fan-control and install it again.
+  * Free up some storage space, uninstall asus-fan-control and install it again.
+  * Contact an asus-fan-control developer." >&2
+    }
+fi
+
 #-------------------------------------------------------------------------------
 # COPYING PREVIOUS CONFIGURATION FILES
 #-------------------------------------------------------------------------------
