Fix uninstallation cleaning of '/etc/rc.local'

diff --git a/make/install b/make/install
--- a/make/install
+++ b/make/install
@@ -16,7 +16,7 @@
 #-------------------------------------------------------------------------------
 
 # list of required software
-SW_REQUIRED='command echo [ id grep chmod sed cp'
+SW_REQUIRED='command echo [ id grep chmod sed cp ls'
 
 # check if some software is missing
 for i in $SW_REQUIRED; do
@@ -62,7 +62,7 @@ POSSIBLE SOLUTIONS:
 fi
 
 # check if installed
-if [ -f "$INSTALL_DIR/ux430ua-fan-control" ]; then
+if [ -x "$INSTALL_DIR/ux430ua-fan-control" ]; then
     echo 'The program is already installed in the given installation directory.'
     exit 0
 fi
@@ -73,11 +73,9 @@ if [ -z "$BUILD_DIR" ]; then
     exit 1
 fi
 
-# check if ux430ua-fan-control file exists
-if [ ! -f "$BUILD_DIR/ux430ua-fan-control" ]; then
-    echo "$0: '$BUILD_DIR/ux430ua-fan-control' does not exist.
-POSSIBLE SOLUTIONS:
-  * Download the project again and repeat the action." >&2
+# check if build directory exists and is not empty
+if [ ! -d "$BUILD_DIR/" ] || [ -z "$(ls -A "$BUILD_DIR/")" ]; then
+    echo "$0: Build directory '$BUILD_DIR/' must exist and must not be empty." >&2
     exit 1
 fi
 
@@ -107,9 +105,10 @@ chmod a+x /etc/rc.local
 
 # copy the program itself
 cp "$BUILD_DIR/ux430ua-fan-control" "$INSTALL_DIR/" &&
+chmod a+x "$INSTALL_DIR/ux430ua-fan-control" &&
 # add script calling to '/etc/rc.local' file to run the program after boot
 sed -i -E -e '/'"$CONTAINS_EXIT_0"'/{s//'"'$INSTALL_DIR_ESCAPED"'\/ux430ua-fan-control'"'"'\n&/; :add_line; N; badd_line}' /etc/rc.local || {
-    echo "$0: It wasn't possible to finish the installation.
+    echo "$0: Can't finish the installation.
 POSSIBLE SOLUTIONS:
   * Free up some storage space.
   * Contact a ux430ua-fan-control developer." >&2
diff --git a/make/uninstall b/make/uninstall
--- a/make/uninstall
+++ b/make/uninstall
@@ -34,6 +34,9 @@ done
 
 INSTALL_DIR="$1"
 
+# escape delimiters of the installation directory path for later use in a sed script
+INSTALL_DIR_ESCAPED="$(echo "$INSTALL_DIR" | sed -E -e 's|/|\\/|g')"
+
 #-------------------------------------------------------------------------------
 # CHECK STATE
 #-------------------------------------------------------------------------------
@@ -45,7 +48,7 @@ if [ -z "$INSTALL_DIR" ]; then
 fi
 
 # check if not installed
-if [ ! -f "$INSTALL_DIR/ux430ua-fan-control" ]; then
+if [ ! -x "$INSTALL_DIR/ux430ua-fan-control" ]; then
     echo 'The program is not installed in the given installation directory.'
     exit 0
 fi
@@ -61,7 +64,11 @@ if [ "$(id -u)" -ne 0 ]; then
 fi
 
 # remove all lines calling the program from '/etc/rc.local'
-sed -i -E -e '/^[[:blank:]]*'"'.*\/ux430ua-fan-control'"'(| .*)$/d' /etc/rc.local
-sed -i -E -e '/^[[:blank:]]*([^[:blank:]]|\\ |\\	)*\/ux430ua-fan-control(| .*)$/d' /etc/rc.local
+sed -i -E -e '/^[[:blank:]]*'"('$INSTALL_DIR_ESCAPED.*\/ux430ua-fan-control'|$INSTALL_DIR_ESCAPED.*\/ux430ua-fan-control)"'(| .*)$/d' /etc/rc.local &&
 # remove the program itself
-rm "$INSTALL_DIR/ux430ua-fan-control"
+rm -f "$INSTALL_DIR/ux430ua-fan-control" || {
+    echo "$0: Can't finish the uninstallation.
+POSSIBLE SOLUTIONS:
+  * Contact a ux430ua-fan-control developer." >&2
+    exit 1
+}
