Improve argument processing

diff --git a/src/asus-fan-control b/src/asus-fan-control
--- a/src/asus-fan-control
+++ b/src/asus-fan-control
@@ -103,14 +103,17 @@ init_config() {
 # PARAMETERS:
 #   $@ - asus-fan-control arguments
 process_args() {
-    case "$1" in # process arguments based on the first argument
-        '') set_temps ;;
-        set-temps) shift && set_temps "$@" ;;
-        get-temps) get_temps ;;
-        help) echo "$HELP_MESSAGE" ;;
-        about) echo "$ABOUT_MESSAGE" ;;
-        *) echo "invalid argument $1" >&2; return 1 ;;
-    esac
+    if [ "$#" -eq 0 ]; then # if no argument given
+        set_temps # apply stored temperatures
+    else
+        case "$1" in # process arguments based on the first argument
+            set-temps) shift && set_temps "$@" ;;
+            get-temps) get_temps ;;
+            help) echo "$HELP_MESSAGE" ;;
+            about) echo "$ABOUT_MESSAGE" ;;
+            *) echo "invalid argument $1" >&2; return 1 ;;
+        esac
+    fi
 }
 
 #-------------------------------------------------------------------------------
