Change 'notebook' to 'laptop'

diff --git a/src/asus-fan-control b/src/asus-fan-control
--- a/src/asus-fan-control
+++ b/src/asus-fan-control
@@ -52,7 +52,7 @@ CONFIG_DIR=/etc/asus-fan-control
 # the base address for fan speed levels configuration
 ACPI_FAN_BASE_ADDR=1335
 
-# fallback temperatures that are about to be used when no notebook model matches
+# fallback temperatures that are about to be used when no laptop model matches
 FALLBACK_TEMPS='55 60 62 65 68 72 76 80'
 
 #-------------------------------------------------------------------------------
@@ -143,17 +143,17 @@ set_acpi_temps() {
 }
 
 # DESCRIPTION:
-#   Returns default temperatures for currently used ASUS notebook model.
+#   Returns default temperatures for currently used ASUS laptop model.
 get_device_default_temps() {
     if [ -r "$DATA_DIR/default-temps" ]; then
         LOCAL_model="$(dmidecode -s system-product-name)"
         LOCAL_temps="$(grep -m 1 -E -e "$LOCAL_model" "$DATA_DIR/default-temps" | cut -f 1-8 -d ' ' )"
         if ! valid_temps "$LOCAL_temps"; then
-            echo "$0: Missing temperatures for your notebook model or they are invalid. Falling back to UX430UA temperatures." >&2
+            echo "$0: Missing temperatures for your laptop model or they are invalid. Falling back to UX430UA temperatures." >&2
             LOCAL_temps="$FALLBACK_TEMPS"
         fi
     else
-        echo "$0: Can't access the file with default temperatures for notebook models. Falling back to UX430UA temperatures." >&2
+        echo "$0: Can't access the file with default temperatures for laptop models. Falling back to UX430UA temperatures." >&2
         LOCAL_temps="$FALLBACK_TEMPS"
     fi
 
